
export const homes = [
    {
      id: 1,
      name: 'homeOne',
      img: '/img/home-1.jpg',
      price: '$695,000',
      detail: '4 bds 3 ba 3,206sqft - House For Sale',
      address: '1234 S. Rose Lane, Somewhere, US 12345',
    },
    {
      id: 2,
      name: 'homeTwo',
      img: '/img/home-2.jpg',
      price: '$599,000',
      detail: '4 bds 3 1/2 ba 2,998sqft - House For Sale',
      address: '4567 W. Village Dr, Somewhere, US 54321',
    },
    {
      id: 3,
      name: 'homeThree',
      img: '/img/home-3.jpg',
      price: '$575,000',
      detail: '4 bds 4 ba 3,401sqft - House For Sale',
      address: '8910 S. Ridge Rd, Somewhere, US 8976',
    },
    {
      id: 4,
      name: 'homeFour',
      img: '/img/home-4.jpg',
      price: '$484,000',
      detail: '4 bds 3 1/2 ba 3,058sqft - House For Sale',
      address: '1112 N. 38th Court, Somewhere, US 88838',
    },
    {
      id: 5,
      name: 'homeFive',
      img: '/img/home-5.jpg',
      price: '$392,000',
      detail: '3 bds 2 ba 2,402sqft - House For Sale',
      address: '1098 E. Stream Blvd, Somewhere, US 45321',
    },
    {
      id: 6,
      name: 'homeSix',
      img: '/img/home-6.jpg',
      price: '$720,000',
      detail: '5 bds 4 ba 5,110sqft - House For Sale',
      address: '6745 W. Nighthawk Way, Somewhere, US 88838',
    },
    {
      id: 7,
      name: 'homeSeven',
      img: '/img/home-7.jpg',
      price: '$590,000',
      detail: '4 bds 3 1/2 ba 3,604sqft - House For Sale',
      address: '2424 S. Creek Avenue, Somewhere, US 98765',
    },
    {
      id: 8,
      name: 'homeEight',
      img: '/img/home-9.jpg',
      price: '$533,000',
      detail: '3 bds 2 ba 3,105sqft - House For Sale',
      address: '3838 N. Dakota St, Somewhere, US 88838',
    },
];

export const agents = [
     {
       id: 1,
       img: '/img/agent-1.jpg',
       name: 'Michael Davis',
       company: 'Find Your Home Realty',
       location: 'Somewhere, US',
       stars: '⭐️ ⭐️ ⭐️ ⭐️ ⭐️',
       experience: '11 years in business',
     },
     {
       id: 2,
       img: '/img/agent-2.jpg',
       name: 'Linda Hammond',
       company: 'RE/MAX Realty',
       location: 'Somewhere, US',
       stars: '⭐️ ⭐️ ⭐️ ⭐️ ⭐️',
       experience: '9 years in business',
     },
     {
       id: 3,
       img: '/img/agent-3.jpg',
       name: 'Dave Thomas',
       company: 'RE/MAX Realty',
       location: 'Somewhere, US',
       stars: '⭐️ ⭐️ ⭐️ ⭐️ ⭐️',
       experience: '18 years in business',
     },
     {
       id: 4,
       img: '/img/agent-4.jpg',
       name: 'Robert Scott',
       company: 'Keller Williams Realty',
       location: 'Somewhere, US',
       stars: '⭐️ ⭐️ ⭐️ ⭐️ ⭐️',
       experience: '5 years in business',
     },
     {
       id: 5,
       img: '/img/agent-5.jpg',
       name: 'Beverly Dixon',
       company: 'Team Dixon Realty',
       location: 'Somewhere, US',
       stars: '⭐️ ⭐️ ⭐️ ⭐️ ⭐️',
       experience: '14 years in business',
     },
     {
       id: 6,
       img: '/img/agent-6.jpg',
       name: 'Shawn Davidson',
       company: 'RE/MAX Realty',
       location: 'Somewhere, US',
       stars: '⭐️ ⭐️ ⭐️ ⭐️ ⭐️',
       experience: '7 years in business',
     },
     {
       id: 7,
       img: '/img/agent-7.jpg',
       name: 'Benjamin Ma',
       company: 'True Estates Realty',
       location: 'Somewhere, US',
       stars: '⭐️ ⭐️ ⭐️ ⭐️ ⭐️',
       experience: '5 years in business',
     },
     {
       id: 8,
       img: '/img/agent-8.jpg',
       name: 'Lisa Bow',
       company: 'Team Dixon Realty',
       location: 'Somewhere, US',
       stars: '⭐️ ⭐️ ⭐️ ⭐️ ⭐️',
       experience: '4 years in business',
     },

]