import Head from 'next/head'
import Image from 'next/image'
import Info from '../components/Info'
import Newsletter from '../components/Newsletter'
import Option from '../components/Option'
import Search from '../components/Search'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mellow: Real Estate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Search />
      <Option />
      <Info />
      <Newsletter />
    </div>
  )
}
